### ISSUE TITLE
HarvestMoon 64 - Screen is cropped to approx 1/4 of expected size

### ISSUE THREAD

**Issue by aaroncarsonart** [mupen64plus/mupen64plus-video-rice#51] opened 2015-03-18 02:23 UTC
I was testing out mupen64 through [OpenEmu](http://openemu.org/) and found that when running Harvest Moon 64, the screen is the wrong size, approximately 1/4 the expected size (in windowed and fullscreen modes).  That is, the actual image is cropped, and thus part of the display is not visible.  I tracked this down to using the rice video plugin.  I duplicated the issues when using mupen 1.9 from [EmuParadise](http://www.emuparadise.me/emulators/files/mupen64plus-bundle-osx-1.99.4.zip) and when using [wxMupen64Plus](https://bitbucket.org/auria/wxmupen64plus/wiki/Home), both when using rice (the game works perfectly using the glide plugin).

Screenshot:
![image](https://cloud.githubusercontent.com/assets/10495264/6701503/e134f390-ccda-11e4-8407-a24a31e108cd.png)

If I can provide any other info, let me know.  I was wondering if this was a known issue, or if there is a specific work-around for this, as I would prefer to use OpenEmu and they only support Rice as a video plugin for Mupen 64.

**Comment by Narann** [comment] 2015-03-19 01:40
Thanks for report, could you provide the MD5 of the ROM please?

Don't be too hasty for a fix but it's always a good thing to keep track of such problem. :)

**Comment by aaroncarsonart** [comment] 2015-03-19 07:30
No worries, figured I would speak up to try to help where I can.
```
$ md5 HarvestMoon64.n64
MD5 (HarvestMoon64.n64) = 0a5d1e13b410d209835b43f2a985ef64
```

**Comment by Narann** [comment] 2015-03-19 13:13
Thanks! mupen64plus print the md5 in its log. I think it's the same but if not, could you send it also. :)

**Comment by aaroncarsonart** [comment] 2015-03-20 07:56
Oh, well I didn't even realize that!  Here's the output when running mupen64plus:
```
Core: Goodname: Harvest Moon 64 (U) [!]
Core: Name: HARVESTMOON64
Core: MD5: 6DA848A70D83ECE130D274124760928E
Core: CRC: 98df9dfc 6606c189
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 16777216 bytes (or 16 Mb or 128 Megabits)
Core: Version: 1449
Core: Manufacturer: Nintendo
Core: Country: USA
```
Looks like the MDF value is different.  Huh, I wonder why

**Comment by conchurnavid** [comment] 2015-03-20 08:10
md5(sum) is calculating over the raw file data. But mupen64plus is calculating over the normalized (reordered) file data. This is necessary because there are three supported file byte orderings ("file formats") which will end up as the same rom in the mupen64plus memory.

Checking the mupen64plus issue tracker (issue 435) makes me believe that the ucode used by harvest moon 64 is not (fully) supported/re-implemented by rice. The way to emulate is to either use a low level graphics plugin+low level rsp plugin or to try glide64mk2.

**Comment by Narann** [comment] 2015-03-21 12:47
Thanks for the precious informations @conchurnavid!

**Comment by searls** [comment] 2015-07-31 14:04
Does anyone have any specific theories about the cause of this? I'd be interested in taking a stab at a PR.

**Comment by aaroncarsonart** [comment] 2016-12-10 06:19
Happy news!  This bug appears to have been fixed in the mupen64plus 2.5 build retrieved from: http://www.emulator-zone.com/doc.php/n64/mupen64plus.html.  I ran the exact same rom with both rice and glide, and the cropping issue is no longer reproducible.  I will leave it to primary contributors to this repo if they want to close this issue, or leave it open.

**Comment by Narann** [comment] 2016-12-10 10:55
Cool! Let's close this! :D

**Closed by Narann** 2016-12-10 10:55 UTC
Labels: game specific

**Comment by Kool-Aid-Kid** [comment] 2018-07-16 06:21
That's odd. I get this issue in version 2.5 on OS X. Anyone else?
